### PR TITLE
if a date mapped object has an explicit null value, its old value is rep...

### PR DESCRIPTION
**Pull request by mitrenegade**
...laced instead of ignored. For issue https://github.com/EasyMapping/EasyMapping/issues/91

### CODE REVIEW

**Comment by DenHeadless** [comment]
Could you elaborate more on why do you think this is a bug? EasyMapping tries to replace every NSNull instance with nil to prevent unwanted crashes and allow more easily handled models and stable behavior. This happens not only for date mapped objects but every kind of object in any mapping.

**Comment by mitrenegade** [comment]
In the next step:

+ (void) setProperty:(EKPropertyMapping *)propertyMapping
            onObject:(id)object
  fromRepresentation:(NSDictionary *)representation
           inContext:(NSManagedObjectContext *)context
{
// (1)
    id value = [self getValueOfManagedProperty:propertyMapping
                            fromRepresentation:representation
                                     inContext:context];
// (2)
    if (value == (id)[NSNull null]) {
        if (![self propertyNameIsScalar:propertyMapping.property fromObject:object]) {
            [self setValue:nil onObject:object forKeyPath:propertyMapping.property];
        }
    } else if (value) {
        [self setValue:value onObject:object forKeyPath:propertyMapping.property];
    }
}

The call at (1) [self getValueOfManagedProperty:...] returns nil if the representation is either null or not sent for a date mapping. The line (2) skips the value setting, so actually the old date value remains. This doesn't happen for regular attributes like strings; for a JSON that is explicitly null for a string property, (1) returns [NSNull null] instead of nil, so (2) correctly sets that attribute to value.
I also made the change so that if the attribute is not sent in the JSON, the change does get skipped rather than getting set to [NSNull null].

I made this change for my specific situation, and wasn't sure how to make a test that would be universal. Please let me know if I can help by doing that. Please test other situations so my change won't negatively affect anyone else. Here is an example of JSON I am processing:

    user =     {
        "created_at" = "2012-01-30T14:37:11Z";
        "delete_request_time" = "<null>";
        email = "bobbyren@gmail.com";
        id = 44898;
        name = "Bobby Ren";
        "profile_picture" = "<null>";
    };

vs 

    user =     {
        "created_at" = "2012-01-30T14:37:11Z";
        "delete_request_time" = "2012-01-30T14:37:11Z";
        email = "bobbyren@gmail.com";
        id = 44898;
        name = "Bobby Ren";
        "profile_picture" = "http://example.com";
    };

**Comment by DenHeadless** [comment]
You could add a date property to Person class, for example, create object from JSON, and then use EKMapper to fill this object with another JSON, that has null values for fields. And test should specifically check, whether property values changed to nil. 

It would be great if you did that for this PR.

Also, i saw a change with managedValueBlock, this serves the same purpose i assume? If yes, tests should be on EKMapper and EKManagedObjectMapper.

**Comment by mitrenegade** [comment]
Great. I will try to add a test and check on both ekmapper and the managed object mapper.

**Comment by mitrenegade** [comment]
i've updated the pull request with some tests.

**Comment by DenHeadless** [comment]
I'm sorry, why did you closed PR? It's no longer relevant? I was going to review changes, when i saw repo is no longer available.

**Comment by mitrenegade** [comment]
oops, meant to comment. must have clicked on close instead.

**Comment by DenHeadless** [comment]
Please reopen PR =) I'm reviewing changes right now.

**Comment by DenHeadless** [comment]
Anyway, changes look good to me, i've merged this fix into master. I'll be releasing new version a bit later, as i want to add something else to new release. 

Thank you for contributing!

**Pull request closed without merging**
